Release nightly k8s resources
keycloak-rel/keycloak-rel pull request #11
Opened 2022-03-25 15:45 UTC by andreaTP

Resolves: https://github.com/keycloak/keycloak/issues/10439

2022-03-25 15:48 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          ref: nightly
@stianst do you mind to create the branch? In this case is a one time operation, or should I automate it as well?

2022-03-25 15:48 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          # TODO: use keycloak-bot here
@stianst do you have idiomatic credentials for the `keycloak-bot` ? Just tell me what to write here 🙂

2022-03-25 15:49 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          token: ${{ secrets.GH_TOKEN }}
Here we assume that `GH_TOKEN` does have write permission on:
https://github.com/keycloak/keycloak-k8s-resources

2022-03-25 18:15 UTC, vmuzikar reviewed
@andreaTP Do you have an example commit how does the result look like?

2022-03-25 18:16 UTC, vmuzikar commented
We might also want to add some how-to-run readme. Not sure if as part of this PR, probably separately.

2022-03-25 18:25 UTC, andreaTP commented
@vmuzikar example commit with mocked resources:
https://github.com/andreaTP/keycloak-k8s-resources/tree/nightly

And the actual content tested in another repo:
https://github.com/andreaTP/keycloak-k8s-release-poc/tree/main/latest/kubernetes

2022-03-25 18:30 UTC, andreaTP commented
Not sure about the "how to run" comment, this CI is only doing integration and is not supposed to be run anywhere else other than in GH action.
Regarding the scheduling etc. of this job we are not introducing any change with this PR.

2022-03-28 07:07 UTC, vmuzikar commented
@andreaTP I meant "how to run" the generated resources. ;) A `kubectl apply -k ...` command, maybe explaining why we need separate kubernetes, minikube, openshift files (starting to thing if we really need them).

2022-03-28 07:53 UTC, andreaTP commented
@vmuzikar thanks for the clarification! Yup, we definitely need something on those lines, but it will probably go in the docs in the main repo, wdyt?

2022-03-28 08:35 UTC, vmuzikar commented
Since this is a separate repo, I'd say the instructions should be present here as well. But as said, let's do it as a follow-up.

2022-03-28 09:15 UTC, vmuzikar requested changes

2022-03-28 09:15 UTC, vmuzikar commented on .github/workflows/nightly.yml
> +          cp -r ../keycloak/operator/target/kubernetes/*.yml kubernetes
The last thing I'm a bit concerned about is that we're releasing separate resources for Kubernetes, Minikube and OpenShift. Sure there are some differences between the files, but I don't think there's anything blocking from using just one of them everywhere. Or am I missing something?

2022-03-28 09:36 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          git push origin refs/tags/nightly --force
I would really like to keep `--force` here.
Everything here is generated, should be idempotent, and, if/when we change how/what we upload it should be simply overwritten; also, in case of "concurrent updates" the desired behaviour is that the last CI will simply overwrite the content.

This is an automated repository and keeping the history of commits is not really interesting.

2022-03-28 09:38 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          cp -r ../keycloak/operator/target/kubernetes/*.yml kubernetes
The `kustomize` setup that we have in the main repo is using `kubernetes.yaml` with a `patchStrategicMerge` on `minikube.yaml` to deploy to `minikube`.
We really want to improve this setup but, at the moment, we are simply shipping all the resources we are generating until we have a better plan ...

2022-03-28 10:19 UTC, vmuzikar commented on .github/workflows/nightly.yml
> +          git push origin refs/tags/nightly --force
Do you have any specific use case that would require `--force`, or is it "just in case"?

For nightlies force push _might_ be ok, but for release process in general I'm not so sure. It just hides potential issues we might have with the flows, silently overwriting stuff. I'd argue that if there are more concurrent flows at the same time, some of them should fail as it is an unexpected state.

> This is an automated repository and keeping the history of commits is not really interesting.

If commits are not important, then why to have it as a git repo in the first place? 😜

2022-03-28 10:23 UTC, vmuzikar commented on .github/workflows/nightly.yml
> +          cp -r ../keycloak/operator/target/kubernetes/*.yml kubernetes
I agree this is a separate issue (how we generate the resources). Let's tackle that separately in https://github.com/keycloak/keycloak/issues/10963.

2022-03-28 10:40 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          cp -r ../keycloak/operator/target/kubernetes/*.yml kubernetes
👍

2022-03-28 10:48 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          git push origin refs/tags/nightly --force
> If commits are not important, then why to have it as a git repo in the first place?

Because it plays well with automation and versioning.

`nightly` is some kind of a "special" job, I would not bother at all at eventually resolving conflicts here.

Anyhow, I'm not going to receive the notification for failed jobs, so let's simply ask @stianst what he prefers 🙂 
Happy to remove the `--force` if he is ok with it!

Additional context:
 - the tag needs to be force pushed as we are updating it and it (usually) exists
 - we can eventually remove the `--force` from the push to the branch

2022-03-31 15:53 UTC, stianst commented on .github/workflows/nightly.yml
> +          git config --global user.email "andrea.peruffo1982@gmail.com"
```suggestion
          git config --global user.email "keycloak.bot@gmail.com"
```

2022-03-31 15:54 UTC, stianst commented on .github/workflows/nightly.yml
> +          git push origin HEAD:refs/heads/nightly --force
I'd be tempted to just drop nightly branch, and just checkout main, and only push that as a tag.

2022-03-31 16:28 UTC, andreaTP commented on .github/workflows/nightly.yml
> +          git push origin HEAD:refs/heads/nightly --force
tentatively kept only the `branch`

2022-04-04 06:13 UTC, stianst approved these changes

2022-04-04 06:13 UTC, merged