Remove node.js release from keycloak server release
keycloak-rel/keycloak-rel pull request #137
Opened 2024-12-12 08:58 UTC by mposolda

closes keycloak/keycloak#35536

2024-12-12 09:15 UTC, jonkoops requested changes
We can probably remove the Node.js repo from the `sync-forks` workflow as well.

2024-12-12 10:22 UTC, mposolda commented
> > We can probably remove the Node.js repo from the `sync-forks` workflow as well.
> 
> I've kept it intentionally as I suppose there is still a chance that we would need it? Similarly I kept quickstarts.
> 
> @stianst proposed yesterday (and AFAIK you are aware of that as well) that we may eventually add "announce" workflows for things like keycloak-client or node.js adapter into keycloak-rel. Those announce workflows might be able to trigger workflows in another repository for increasing versions (like for example trigger this workflow in quickstarts https://github.com/keycloak/keycloak-quickstarts/actions/workflows/update-nodejs-adapter-version.yml .
> 
> So maybe ok to keep it for now and eventually remove in the future if we really don't need it?

Discussed with @stianst to eventually remove node.js from `sync forks` as a follow-up (once we have node.js release process ready)

2024-12-12 11:23 UTC, mposolda commented on .github/workflows/branch-create.yml
+1, removed that. Thanks for pointing this!

2024-12-12 11:57 UTC, jonkoops commented
> So maybe ok to keep it for now and eventually remove in the future if we really don't need it?

Sounds good, and yes the announce workflows will have to be added to the individual repositories.

2024-12-12 11:57 UTC, jonkoops approved these changes
LGTM!

2024-12-13 08:32 UTC, mposolda commented
> > So maybe ok to keep it for now and eventually remove in the future if we really don't need it?
> 
> Sounds good, and yes the announce workflows will have to be added to the individual repositories.

@jonkoops Thanks for the review!

AFAIK @stianst mentioned the announce workflows may be present rather in the `keycloak-rel` repository. The reason is, that announce workflow may require `GH_TOKEN` secret to be present in the repository, which triggers the workflow. The `GH_TOKEN` is needed in case that repository needs to deal with other repositories. And Stian mentioned that managing `GH_TOKEN` secrets is a pain (they need to be periodically rotated etc), so the preferred way is to have this secret just in the `keycloak-rel` repository (where the `GH_TOKEN` secret is already present).

So maybe we can have like:
- As step 1, we can have workflows like "Increase keycloak-client version" in the individual repositories like `keycloak-quickstarts` or `keycloak-web` (For `keycloak-quickstarts`, we already have it for increasing version of keycloak-client or node.js adapters)
- From the longer term, we can have announce workflows in the `keycloak-rel` like "Announce keycloak client", which would be able to trigger the workflows from above

2024-12-13 12:46 UTC, jonkoops commented
@mposolda sounds like a good proposal, let's go with that approach for now.

2025-01-20 08:11 UTC, stianst approved these changes

2025-01-20 08:11 UTC, merged