Fix nightly
keycloak-rel/keycloak-rel pull request #45
Opened 2022-08-01 15:58 UTC by vmuzikar

Supersedes #43.

It's not a super nice solution but if we want to avoid [external dependencies](https://github.com/andymckay/cancel-action/tree/0.2), this is the most straightforward way.

2022-08-01 16:02 UTC, jonkoops requested changes

2022-08-01 16:02 UTC, jonkoops commented on .github/workflows/release-nightly.yml
> +    if: github.repository_owner == 'keycloak-rel'
This is the only place this is needed as all of the subsequent steps are dependent on this job. Thus if this job is skipped so are all others.

2022-08-01 16:04 UTC, vmuzikar commented on .github/workflows/release-nightly.yml
> +    if: github.repository_owner == 'keycloak-rel'
Good point, thank you.

2022-08-01 16:06 UTC, jonkoops approved these changes

2022-08-01 19:09 UTC, abstractj approved these changes

2022-08-02 11:13 UTC, stianst requested changes

2022-08-02 11:13 UTC, stianst commented on .github/workflows/release-nightly.yml
> +    if: github.repository_owner == 'keycloak-rel'
Need to check if it's a scheduled event as we need to be able to run nightly flow manually on test fork

2022-08-02 12:36 UTC, jonkoops commented on .github/workflows/release-nightly.yml
> +    if: github.repository_owner == 'keycloak-rel'
```suggestion
    if: github.event_name != 'schedule' || github.repository_owner == 'keycloak-rel'
```

2022-08-03 06:52 UTC, vmuzikar commented
@stianst @jonkoops Thanks for the review! Applied the suggestion.

2022-08-03 10:12 UTC, jonkoops approved these changes

2022-08-03 21:07 UTC, abstractj approved these changes

2022-08-03 21:08 UTC, merged