Add Node.js Connect to the release
keycloak-rel/keycloak-rel pull request #69
Opened 2022-10-25 13:04 UTC by jonkoops

Closes #29

2022-10-26 06:49 UTC, stianst commented on .github/workflows/release-nightly.yml
> +    needs: [env, create-tags]
Doesn't the admin console require the nodejs-admin client to be built first?

2022-10-26 06:50 UTC, stianst commented on .github/workflows/release.yml
> +    needs: [env, create-tags]
Same question as above

2022-10-26 11:56 UTC, jonkoops commented on .github/workflows/release-nightly.yml
> +    needs: [env, create-tags]
We're not actually using the version uploaded here. We have a [profile to do so](https://github.com/keycloak/keycloak-ui/blob/7730509796a3fe2d1703385e39823a20f4cc2983/keycloak-theme/pom.xml#L195-L231), but it is not used anywhere.

I've removed it here to avoid implying this relation actually exists, it might cause people to assume they are dependent when it is not.

2022-10-26 11:56 UTC, jonkoops commented on .github/workflows/release-nightly.yml
> +    needs: [env, create-tags]
Also when we monorepo stuff this problem will go away.

2022-10-26 12:55 UTC, abstractj commented
@jonkoops please correct me if I'm wrong, but it seems to me that the changes proposed here are addressing 2 issues:

1. Add Node.js Connect to the release
2. Changes in the admin console

Is that true? Checking to have more clarity before reviewing it.

2022-10-26 16:14 UTC, jonkoops commented
1. Yes.
2. This removes the dependency between the jobs of the Admin Client and the Admin UI.

Reason being that these don't actually depend on each other as the version of the Admin Client used in the Admin UI is one that is already published to NPM. The release process does not actually install the tarball created in this process to the Admin UI.

Once all this stuff is monorepo-ed it doesn't actually matter anymore as the latest version is always used, as it is already in the same workspace. Meaning it no longer has to be published for our own internal components.

2022-10-27 14:08 UTC, jonkoops commented
@stianst @abstractj I've restored the dependency between the Admin UI and client, since it is causing to much confusion.

2022-10-27 19:53 UTC, abstractj approved these changes

2022-10-28 08:41 UTC, stianst approved these changes

2022-10-28 08:59 UTC, stianst requested changes
Changes looks good, will merge after test runs compete (and hopefully passes)

2022-10-31 23:05 UTC, jonkoops commented
@stianst looks like both have passed

2022-11-01 10:07 UTC, stianst approved these changes

2022-11-01 10:08 UTC, merged